### ISSUE TITLE
当操作系统的locale为English时，无法启用VC-LTL

### ISSUE THREAD

**Issue by biiaidt** [Chuyu-Team/VC-LTL#57]
**当操作系统的current system locale为English(United States) 时，VC-LTL在VS15,17,19中均无法生效**

**重现步骤**
1. 修改current system locale,为英文，
![image](https://user-images.githubusercontent.com/8305778/63923441-2741fb80-ca79-11e9-88d8-4b2b5dc591b2.png)

**环境信息：（Information）**
 - OS: Window 10 64(10.0.17763.678) 
 - VC-LTL Version: 4.0.1.10
 - VC Tools Version: 14.16.27023
 - UCRT Version  : 10.0.17763.0
 - Platform : x86

**该问题通过将locale改成中文VC-LTL正常运行。）**

**Comment by mingkuang-Chuyu** [comment]
请问哪种方式 无法使用？VC-LTL有好几种方式啊……

**Comment by biiaidt** [comment]
emmm, 抱歉没有太明白的说使用环境，我只在标题里面提了一下。

使用VS进行测试的， 然后测试的工程是：[VisualStudioConsoleDemo](https://github.com/Chuyu-Team/vc-ltl-samples/tree/master/VisualStudioConsoleDemo)。

具体现象就是，在locale为English时，编译这个工程无法启用VC-LTL。同样我也用来测试过我自己的项目，仍然没有成功。将locale切换成Chinese的时候才成功的。

我猜测是字符集出现了问题，因为我看到部分文件里面出现了大量的中文。

**Comment by mingkuang-Chuyu** [comment]
抱歉，无法重新，虽然有很多中文，但是文件本身是UTF8，所以也能正常输出。
另外国外的自动化编译平台都是英文版系统，他们也能正常使用啊。

建议你重新确认下，另外还请提供详细错误信息。

**Comment by mingkuang-Chuyu** [comment]
1>  ◆                                                                                                ◆
1>  ◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆
1>  
1>  VC-LTL Path      : I:\Visual Studio 2015\VC-LTL\
1>  VC Tools Version : 14.22.27905
1>  UCRT Version     : 10.0.18362.0
1>  Platform         : x86
1>  Using VC-LTL Vista Advanced Mode
1>VisualStudioConsoleDemo.cpp
1>I:\Visual Studio 2015\VC-LTL\config\Vista\LTL_config.h(27): message :  进入ltl Vista模式，已准备引用到VC-LTL。定义 _DISABLE_DEPRECATE_LTL_MESSAGE 可关闭信息提示。
1>Generating code
1>Previous IPDB not found, fall back to full compilation.
1>All 4 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
1>Finished generating code
1>VisualStudioConsoleDemo.vcxproj -> F:\vc-ltl-samples-master\VisualStudioConsoleDemo\Release\VisualStudioConsoleDemo.exe
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

**Comment by mingkuang-Chuyu** [comment]
现在已经无法重新问题了……暂时关了吧。以后再说
